export const rowData = [
  {
    marketplace: "USA",
    shortName: "NaturalThings Main",
    autoPilot: 369,
    spend: 1087.54,
    spendChange: 20.34,
    sales: 1087.54,
    salesChange: 20.34,
    acos: 70.32,
    acosChange: 20.34,
    units: 94,
    unitsChange: -20.34,
    clicks: 122,
    clicksChange: 29.34,
  },
  {
    marketplace: "Canada",
    shortName: "NaturalThings",
    autoPilot: 74,
    spend: 1087.54,
    spendChange: 20.34,
    sales: 1087.54,
    salesChange: -20.34,
    acos: 10.32,
    acosChange: -29.34,
    units: 65,
    unitsChange: 29.34,
    clicks: 122,
    clicksChange: -29.34,
  },
  {
    marketplace: "Germany",
    shortName: "NaturalThings Europe",
    autoPilot: 0,
    spend: 1087.54,
    spendChange: 20.34,
    sales: 0,
    salesChange: 0,
    acos: 70.32,
    acosChange: -20.34,
    units: 75,
    unitsChange: 55.34,
    clicks: 122,
    clicksChange: 29.34,
  },
  {
    marketplace: "India",
    shortName: "Natural Things",
    autoPilot: 3,
    spend: 0,
    spendChange: 0,
    sales: 0,
    salesChange: 0,
    acos: 0,
    acosChange: 0,
    units: 0,
    unitsChange: 0,
    clicks: 0,
    clicksChange: 0,
  },
  {
    marketplace: "Netherlands",
    shortName: "NaturalThings Europe",
    autoPilot: 0,
    spend: 0,
    spendChange: 0,
    sales: 0,
    salesChange: 0,
    acos: 0,
    acosChange: 0,
    units: 0,
    unitsChange: 0,
    clicks: 0,
    clicksChange: 0,
  },
  {
    marketplace: "Germany",
    shortName: "Natural Things",
    autoPilot: 0,
    spend: 1087.54,
    spendChange: 20.34,
    sales: 0,
    salesChange: 0,
    acos: 0,
    acosChange: 0,
    units: 0,
    unitsChange: 0,
    clicks: 0,
    clicksChange: 0,
  },
  {
    marketplace: "Italy",
    shortName: "NaturalThings Main",
    autoPilot: 1,
    spend: 0,
    spendChange: 20.34,
    sales: 0,
    salesChange: 0,
    acos: 0,
    acosChange: 0,
    units: 0,
    unitsChange: 0,
    clicks: 0,
    clicksChange: 0,
  },
];
